title: Chirpy
tagline: A text-focused Jekyll theme.
description: >-
  A minimal, portfolio, sidebar, bootstrap Jekyll theme with responsive web
  design and focuses on text presentation.
url: ''
author: your_full_name
avatar: /assets/img/sample/avatar.jpg
github:
  username: github_username
twitter:
  username: twitter_username
social:
  name: your_full_name
  email: example@doamin.com
  links:
    - 'https://twitter.com/username'
    - 'https://github.com/username'
google_site_verification: google_meta_tag_verification
baseurl: ''
timezone: Asia/Shanghai
google_analytics:
  id: ''
  pv:
    enabled: false
    proxy_url: ''
    proxy_endpoint: ''
    cache: false
disqus:
  comments: false
  shortname: ''
theme_mode: null
toc: true
paginate: 10
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
permalink: '/posts/:title/'
collections:
  tabs:
    output: true
    sort_by: order
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      breadcrumb:
        - label: Posts
          url: /
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: index.html
    values:
      breadcrumb:
        - label: Posts
  - scope:
      path: tags
    values:
      breadcrumb:
        - label: Home
          url: /
        - label: Tags
          url: /tabs/tags/
  - scope:
      path: categories
    values:
      breadcrumb:
        - label: Home
          url: /
        - label: Categories
          url: /tabs/categories/
  - scope:
      path: ''
      type: tabs
    values:
      layout: page
      dynamic_title: true
      breadcrumb:
        - label: Home
          url: /
sass:
  sass_dir: /assets/css
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: []
exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - tools
  - docs
  - README.md
  - LICENSE
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: '/tags/:name/'
    category: '/categories/:name/'
